spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

  # ?? ?? ??
  logging:
    level:
      # hibernate ? ??? ?? ??? debug??? ??
      # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
      org.hibernate.SQL: debug
      org.hibernate.type: trace # ?? ???? ????? ???? ??

  cache:
    type: redis
    redis:
      cache-null-values: true

